

const ALLOWED_STAGES = new Set([
    '$match',
    '$group',
    '$lookup',
    '$sort',
    '$limit',
    '$project',
    '$unwind',
    '$count',
    '$addFields',   // read-only computed fields — commonly generated by AI
    '$set',         // alias for $addFields — read-only computed fields
    '$replaceRoot', // restructure documents — read-only
    '$replaceWith', // alias for $replaceRoot — read-only
    '$skip',        // pagination — read-only
    '$bucket',      // grouping/binning — read-only
    '$facet',       // multi-faceted aggregation — read-only
    '$sample',      // random sampling — read-only
]);

const FORBIDDEN_STRINGS = [
    '$out',
    '$merge',
    '$function',
    '$accumulator',
    'mapReduce',
    'eval'
];


const containsDangerousContent = (obj) => {
    if (obj === null || obj === undefined) return false;

    if (typeof obj === 'string') {
        const lowerStr = obj.toLowerCase();
        for (const forbidden of FORBIDDEN_STRINGS) {
            if (lowerStr.includes(forbidden.toLowerCase())) {
                return true;
            }
        }
        return false;
    }

    if (Array.isArray(obj)) {
        for (const item of obj) {
            if (containsDangerousContent(item)) return true;
        }
        return false;
    }

    if (typeof obj === 'object') {
        for (const key of Object.keys(obj)) {
            // Check key names
            for (const forbidden of FORBIDDEN_STRINGS) {
                if (key.toLowerCase().includes(forbidden.toLowerCase())) {
                    return true;
                }
            }
            if (containsDangerousContent(obj[key])) return true;
        }
        return false;
    }

    return false;
};


const validatePipeline = (pipeline) => {
    if (!Array.isArray(pipeline)) {
        return { valid: false, error: "Pipeline must be an array." };
    }

    if (pipeline.length === 0) {
        return { valid: false, error: "Pipeline cannot be empty." };
    }

    if (pipeline.length > 20) {
        return { valid: false, error: "Pipeline exceeds maximum stage limit of 20 stages." };
    }

    for (let i = 0; i < pipeline.length; i++) {
        const stage = pipeline[i];
        if (typeof stage !== 'object' || stage === null) {
            return { valid: false, error: `Invalid stage at index ${i}.` };
        }

        const keys = Object.keys(stage);
        if (keys.length !== 1) {
            return { valid: false, error: `Each stage must contain exactly one operator at index ${i}.` };
        }

        const operator = keys[0];
        if (!ALLOWED_STAGES.has(operator)) {
            return { valid: false, error: `Unauthorized pipeline operator "${operator}" at index ${i}. Only read-only operations are allowed.` };
        }


        if (operator === '$lookup') {
            const lookup = stage['$lookup'];
            if (!lookup || typeof lookup !== 'object') {
                return { valid: false, error: `Malformed $lookup operator at index ${i}.` };
            }

            if (lookup.from !== 'users') {
                return { valid: false, error: `Unauthorized join target "${lookup.from}" in $lookup at index ${i}. Can only join with "users" collection.` };
            }
        }


        if (containsDangerousContent(stage)) {
            return { valid: false, error: `Dangerous operators or strings detected in stage at index ${i}.` };
        }
    }

    return { valid: true };
};

module.exports = { validatePipeline };
