services:

  database:
    image: mongo:6.0
    container_name: tasksutra_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tasksutra_network

  # Backend API Service
  backend:
    build: ./backend
    container_name: tasksutra_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
    depends_on:
      - database
    networks:
      - tasksutra_network

  # Frontend Web Service
  frontend:
    build: ./frontend
    container_name: tasksutra_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tasksutra_network

volumes:
  mongo_data:

networks:
  tasksutra_network:
    driver: bridge
