name: CI/CD Pipeline

on:
  push:
    branches: [main, feature/dockerization]
  pull_request:
    branches: [main]

jobs:
  test-builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: |
          docker build -t tasksutra-backend:latest ./backend

      - name: Build Frontend Docker Image
        run: |
          docker build -t tasksutra-frontend:latest ./frontend
